name: Deploy smart-contract

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: environment
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Smart Contracts
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: echo ${{ vars.RPC_URL }}

      - name: Run Forge build
        run: |
          forge build --sizes

      - name: Predict Contract Addresses
        run: |
          forge script script/PredictAddresses.s.sol \
          --rpc-url ${{ vars.RPC_URL }} \
          --private-key ${{ secrets.PRIVATE_KEY }} \
          --create2-deployer ${{ vars.CREATE2_ADDR }} \
          --broadcast
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SALT_SUFFIX: ${{ github.event.inputs.environment }}_${{ github.sha }}

      - name: Deploy Upgradeable Contracts
        id: deploy
        run: |
          forge script script/DeployUpgradeable.s.sol \
            --rpc-url ${{ vars.RPC_URL }} \
            --private-key ${{ secrets.PRIVATE_KEY }} \
            --create2-deployer ${{ vars.CREATE2_ADDR }} \
            --broadcast > logs.out
          cat logs.out >> "$GITHUB_OUTPUT"
        env:
          SALT_SUFFIX: ${{ github.event.inputs.environment }}_${{ github.sha }}
      - name: Send message to Deploy channel
        id: matrix-chat-message
        uses: fadenb/matrix-chat-message@v0.0.6
        with:
          homeserver: ${{ secrets.MATRIC_SERVER }}
          token: ${{ secrets.MATRIX_TOKEN }}
          channel: "!SqJrmVXmqVLONxfaDe:matrix.joyslab.org"
          message: |
            # 📦 [EVM] L2 Contracts Deployment ✅

            ## Details:
            ```
             ${{ steps.deploy.outputs.msg }}
            ```
